#!/bin/bash
packer build -force -only vmware-iso.ubuntu ubuntu.pkr.hcl

exit 0

build pkrvariablesfilesname.pkrvars.hcl ?
build vmw arm
build qemu arm
build docker arm
build vmw amd64
build qemu amd64
build docker amd64

